import { useEffect, useMemo, useState } from 'react';
import {
  Orbit, Loader2, AlertTriangle, Search, ChevronDown, Sparkles,
  RotateCcw, Info, Atom, Axis3d, Wand2, FileDown, ListTree, XCircle, Radio,
} from 'lucide-react';
import SymmetryElementsViewer, { KIND_META } from '../components/Viewer3D/SymmetryElementsViewer';
import { Reveal, StaggerGroup, Word, InlineReveal } from '../components/motion/ScrollReveal';
import { fetchSymmetryDemos, analyzeSymmetry, analyzeSymmetryFromPubchem, extractErrorMessage } from '../api/api';
import { symmetryAtomsToMolBlock } from '../lib/symmetryMolblock';
import './GroupTheoryPage.css';

const PLACEHOLDER = `3
water
O 0 0 0
H 0.757 0.586 0
H -0.757 0.586 0`;

const OP_KIND_LABEL = { E: 'Identity', C: 'Rotation', i: 'Inversion', M: 'Mirror plane', S: 'Improper rotation' };

// Builds a self-contained Markdown report from an analysis result and
// triggers a browser download — no server round-trip needed, since every
// field it uses is already sitting in `result` from the /analyze response.
function downloadSymmetryReport(result) {
  if (!result) return;
  const lines = [];
  lines.push(`# Symmetry report — ${result.groupPretty}`);
  lines.push('');
  lines.push(`**Formula:** ${result.formulaPretty}  `);
  lines.push(`**Atoms:** ${result.atomCount}  `);
  lines.push(`**Point group:** ${result.groupPretty}${result.groupDescription ? ` — ${result.groupDescription}` : ''}`);
  lines.push('');
  lines.push('## Detection summary');
  lines.push('');
  lines.push(`- Group order: ${result.orderLabel ? `${result.orderLabel} (infinite)` : `${result.detectedOps} / ${result.expectedOrder}`}`);
  lines.push(`- Inversion center: ${result.inversion ? 'yes' : 'no'}`);
  lines.push(`- Mirror planes: ${result.mirrorCount}`);
  lines.push(`- Improper rotations: ${result.improperRotationCount}`);
  lines.push(`- Rotational orders found: ${result.rotationalOrders?.join(', ') || 'none'}`);
  lines.push(`- Linear molecule: ${result.linear ? 'yes' : 'no'}`);
  lines.push(`- Tolerance used: ${result.tolerance} \u00c5`);
  lines.push(`- Worst match error: ${result.maxError} \u00c5`);
  if (typeof result.symmetryScore === 'number') lines.push(`- Symmetry score: ${result.symmetryScore}%`);
  if (result.distortionWarning) lines.push(`- \u26a0\ufe0f ${result.distortionWarning}`);
  lines.push('');
  if (result.decisionTrace?.length) {
    lines.push('## Why this point group');
    lines.push('');
    result.decisionTrace.forEach((line, i) => lines.push(`${i + 1}. ${line}`));
    lines.push('');
  }
  if (result.rejectedTests?.length) {
    lines.push('## Symmetry tests that did not pass');
    lines.push('');
    lines.push('| Element tested | Closest miss |');
    lines.push('|---|---|');
    result.rejectedTests.forEach((t) => lines.push(`| ${t.label} | ${t.errorAngstrom} \u00c5 |`));
    lines.push('');
  }
  if (result.representation) {
    const rep = result.representation;
    lines.push('## Representation reduction');
    lines.push('');
    lines.push(`- \u0393(3N) = ${rep.gamma3N}`);
    lines.push(`- \u0393(trans) = ${rep.gammaTrans}`);
    lines.push(`- \u0393(rot) = ${rep.gammaRot}`);
    lines.push(`- **\u0393(vib) = ${rep.gammaVib}**`);
    lines.push('');
    if (rep.validation) {
      const v = rep.validation;
      lines.push(`- Validation: \u0393(3N) accounts for ${v.gamma3NDimension}/${v.expectedDimension} Cartesian degrees of freedom` +
        `${v.gamma3NMatchesAtomCount && v.decompositionConsistent ? ' \u2713' : ' \u2014 mismatch, treat this result with caution'}.`);
      lines.push('');
    }
    if (rep.spectroscopy?.length) {
      lines.push('### IR / Raman activity');
      lines.push('');
      lines.push('| Irrep | Modes | IR active | Raman active |');
      lines.push('|---|---|---|---|');
      rep.spectroscopy.forEach((s) => lines.push(`| ${s.irrep} | ${s.count} | ${s.irActive ? 'yes' : 'no'} | ${s.ramanActive ? 'yes' : 'no'}${s.silent ? ' (silent)' : ''} |`));
      lines.push('');
    }
  } else if (result.representationError) {
    lines.push(`## Representation reduction`);
    lines.push('');
    lines.push(`Not available: ${result.representationError}`);
    lines.push('');
  }
  lines.push('---');
  lines.push(`*Generated by the Group Theory tab \u00b7 tolerance ${result.tolerance} \u00c5*`);

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `symmetry-report-${(result.formulaPretty || 'structure').replace(/[^a-z0-9]+/gi, '-')}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const TICKER_ITEMS = [
  'SCHOENFLIES NOTATION', 'POINT GROUPS', 'CHARACTER TABLES', 'IRREDUCIBLE REPRESENTATIONS',
  '\u0393\u2083\u2099 REDUCTION', 'MIRROR PLANES', 'ROTATION AXES',
];

// The last molecule the user looked at is remembered here so the page never
// opens on an empty "paste something" state — it always reopens on whatever
// was last on screen (or, the very first time, an auto-analyzed default).
const LAST_MOLECULE_KEY = 'gt:lastMolecule:v1';

function loadLastMolecule() {
  try {
    const raw = localStorage.getItem(LAST_MOLECULE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed.structure === 'string') return parsed;
  } catch {
    // ignore corrupt/unavailable storage — falls back to the placeholder
  }
  return null;
}

function saveLastMolecule(data) {
  try {
    localStorage.setItem(LAST_MOLECULE_KEY, JSON.stringify(data));
  } catch {
    // storage full/unavailable — not worth surfacing to the user
  }
}

export default function GroupTheoryPage() {
  // Read once, synchronously, so the very first render already has
  // whichever molecule the user left the page on last time.
  const [saved] = useState(() => loadLastMolecule());

  const [demos, setDemos] = useState([]);
  const [structure, setStructure] = useState(saved?.structure || PLACEHOLDER);
  const [tolerance, setTolerance] = useState(saved?.tolerance ?? 0.08);
  const [pubchemQuery, setPubchemQuery] = useState(saved?.pubchemQuery || '');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(saved?.result || null);
  const [pubchemMeta, setPubchemMeta] = useState(saved?.pubchemMeta || null);
  const [showDerivation, setShowDerivation] = useState(false);
  const [hoveredOp, setHoveredOp] = useState(null);
  const [pinnedOp, setPinnedOp] = useState(null);
  const [playRequest, setPlayRequest] = useState(null); // { label, token } — token forces a replay even on the same label
  const activeHighlight = hoveredOp || pinnedOp;

  // A fresh analysis invalidates any pinned/hovered operation label from
  // the previous structure (it may not even exist in the new one).
  useEffect(() => {
    setHoveredOp(null);
    setPinnedOp(null);
    setPlayRequest(null);
  }, [result]);

  useEffect(() => {
    let cancelled = false;
    fetchSymmetryDemos()
      .then((data) => { if (!cancelled) setDemos(data); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, []);

  // First-ever visit (nothing saved yet): don't leave the results panel
  // empty — auto-run the placeholder so there's always a molecule showing.
  useEffect(() => {
    if (!saved) runAnalyze(PLACEHOLDER);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Whenever a new result lands, remember it (with the structure/tolerance/
  // query that produced it) so reopening the page picks up right here.
  useEffect(() => {
    if (!result) return;
    saveLastMolecule({ structure, tolerance, pubchemQuery, result, pubchemMeta });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [result]);

  const runAnalyze = async (text = structure) => {
    setLoading(true);
    setError(null);
    setPubchemMeta(null);
    try {
      const r = await analyzeSymmetry(text, tolerance);
      setResult(r);
    } catch (err) {
      setError(extractErrorMessage(err, "Couldn't analyze that structure."));
      setResult(null);
    } finally {
      setLoading(false);
    }
  };

  const runPubchem = async () => {
    if (!pubchemQuery.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const r = await analyzeSymmetryFromPubchem(pubchemQuery.trim(), tolerance);
      setResult(r);
      setStructure(r.sourceStructure || structure);
      setPubchemMeta({ cid: r.pubchemCid, url: r.pubchemUrl });
    } catch (err) {
      setError(extractErrorMessage(err, 'Could not fetch that compound from PubChem.'));
      setResult(null);
    } finally {
      setLoading(false);
    }
  };

  const loadDemo = (demo) => {
    setStructure(demo.xyz);
    setPubchemQuery('');
    setPubchemMeta(null);
    runAnalyze(demo.xyz);
  };

  const molBlock = useMemo(() => {
    if (!result?.atoms?.length) return null;
    return symmetryAtomsToMolBlock(result.atoms, result.bonds || [], result.formulaPretty || 'Structure');
  }, [result]);

  const opGroups = useMemo(() => {
    if (!result?.operations) return [];
    const byKind = new Map();
    for (const op of result.operations) {
      if (!byKind.has(op.kind)) byKind.set(op.kind, []);
      byKind.get(op.kind).push(op.label);
    }
    return [...byKind.entries()];
  }, [result]);

  // While this page is mounted, force the surrounding <html>/<body> to the
  // same paper-cream color as the page itself. The rest of the app is a
  // dark "lab" theme (see index.css), so without this, any sliver of body
  // background that peeks past the page content — wide-viewport side
  // margins, mobile overscroll/rubber-banding above or below the page —
  // showed the dark theme through. The navbar is a separate fixed element
  // and keeps its own dark background on purpose.
  useEffect(() => {
    document.documentElement.classList.add('gt-light-scroll');
    document.body.classList.add('gt-light-scroll');
    return () => {
      document.documentElement.classList.remove('gt-light-scroll');
      document.body.classList.remove('gt-light-scroll');
    };
  }, []);

  const bondCount = result?.bonds?.length ?? 0;
  const liveStatusLine = pubchemMeta
    ? `PubChem CID ${pubchemMeta.cid} \u00b7 3-D structure loaded into the simulator \u00b7 point group ${result?.groupPretty} \u00b7 ${result?.atomCount} atoms \u00b7 ${bondCount} bonds`
    : result
    ? `3-D structure loaded into the simulator \u00b7 point group ${result.groupPretty} \u00b7 ${result.atomCount} atoms \u00b7 ${bondCount} bonds`
    : null;

  return (
    <div className="gt-page min-h-screen w-full overflow-x-clip">
    <div className="mx-auto w-full max-w-[1680px] overflow-x-clip px-4 pb-24 pt-6 sm:px-6 lg:px-10">
      {/* ---------------- hero ---------------- */}
      <div className="gt-section gt-section-paper relative mb-6 px-5 py-8 sm:px-9 sm:py-12">
        <div
          className="gt-hero-diamond pointer-events-none absolute -left-6 top-10 hidden h-10 w-10 border-2 border-[var(--gt-ink)]/25 sm:block"
          aria-hidden="true"
        />

        <div className="relative z-10 grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-center">
          <div>
            <Reveal trigger="mount" className="gt-kicker mb-4">
              <span className="gt-kicker-num">01</span> Symmetry lab
            </Reveal>

            <StaggerGroup as="h1" trigger="mount" className="gt-heading text-3xl sm:text-5xl lg:text-6xl">
              <Word>Find</Word> <Word>the</Word>{' '}
              <InlineReveal as="span" className="gt-mark">symmetry</InlineReveal>{' '}
              <Word>hiding</Word> <Word>in</Word> <Word>any</Word> <Word>molecule.</Word>
            </StaggerGroup>

            <Reveal trigger="mount" delay={0.2} as="p" className="mt-4 max-w-xl text-sm leading-relaxed text-[var(--gt-ink-soft)] sm:text-[15px]">
              Paste a 3-D structure (XYZ, SDF/MOL, or PDB), or pull one straight from PubChem. This
              engine finds the real symmetry operations of the geometry, classifies the point group
              from them, and reduces the 3N Cartesian representation into
              {' '}&Gamma;<sub>trans</sub> + &Gamma;<sub>rot</sub> + &Gamma;<sub>vib</sub>.
            </Reveal>

            <Reveal trigger="mount" delay={0.3} className="mt-5 flex flex-wrap items-center gap-2">
              <span className="gt-chip"><Wand2 size={12} /> Real operation detection, not a lookup table</span>
              <span className="gt-chip"><Axis3d size={12} /> Rotate, hover, and play out each operation</span>
            </Reveal>
          </div>

          <Reveal trigger="mount" delay={0.15} direction="left" className="hidden lg:block">
            <GTHeroGraphic />
          </Reveal>
        </div>

        <div className="gt-ticker-row relative z-10 mt-8 border-t-2 border-[var(--gt-ink)] pt-3">
          <div className="gt-ticker-track">
            {[...TICKER_ITEMS, ...TICKER_ITEMS].map((t, i) => (
              <span key={i} className="mx-4 font-display text-[11px] font-bold uppercase tracking-widest text-[var(--gt-ink-soft)]">
                {t} <span className="text-[var(--gt-orange)]">&middot;</span>
              </span>
            ))}
          </div>
        </div>
      </div>

      <div className="grid gap-5 lg:grid-cols-[minmax(0,420px)_1fr]">
        {/* ---------------- input panel ---------------- */}
        <div className="space-y-5">
          <div className="gt-section gt-section-light relative px-4 py-5 sm:px-5 sm:py-6">
            <div className="relative z-10">
              <span className="gt-live-badge">
                <span className="gt-live-dot" /> Live 3-D workspace
              </span>

              <h2 className="gt-heading mt-3 text-lg text-[var(--gt-ink)] sm:text-xl">
                Find a molecule&rsquo;s point group
              </h2>
              <p className="mt-1.5 text-[12px] leading-relaxed text-[var(--gt-ink)]/70">
                Paste an XYZ, SDF/MOL or PDB structure. The solver searches the 3-D geometry for
                rotations, reflections, inversion and improper rotations, generates the operation
                group, and classifies the point group.
              </p>

              <label className="mb-2 mt-4 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink)]/80">
                <Atom size={13} /> XYZ / SDF / PDB
              </label>
              <textarea
                value={structure}
                onChange={(e) => setStructure(e.target.value)}
                rows={9}
                spellCheck={false}
                className="gt-textarea text-xs"
              />

              <div className="mt-3 flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between">
                <label className="gt-tolerance-box">
                  <span className="text-[var(--gt-ink)]/70">Tolerance</span>
                  <input
                    type="number"
                    min={0.01}
                    max={0.3}
                    step={0.01}
                    value={tolerance}
                    onChange={(e) => setTolerance(parseFloat(e.target.value) || 0)}
                  />
                  <span className="text-[var(--gt-ink)]/70">&Aring;</span>
                </label>
                <button onClick={() => runAnalyze()} disabled={loading} className="gt-btn w-full justify-center sm:w-auto">
                  {loading ? <Loader2 size={15} className="animate-spin" /> : <Sparkles size={15} />}
                  Calculate point group
                </button>
              </div>
              <p className="mt-3 text-[11px] leading-relaxed text-[var(--gt-ink)]/60">
                Larger tolerance forgives noisier/optimized coordinates but can over-detect symmetry; lower it for a stricter read.
              </p>

              {liveStatusLine && (
                <div className="gt-status-line mt-4">
                  <span className="gt-live-dot" />
                  <span>
                    {liveStatusLine}
                    {pubchemMeta && (
                      <>
                        {' \u00b7 '}
                        <a href={pubchemMeta.url} target="_blank" rel="noopener noreferrer" className="underline decoration-dotted underline-offset-2">
                          Open PubChem record
                        </a>
                      </>
                    )}
                  </span>
                </div>
              )}
            </div>
          </div>

          <div className="gt-card p-4 sm:p-5">
            <label className="mb-2 block text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink-soft)]">
              Fetch from PubChem
            </label>
            <div className="flex gap-2">
              <input
                value={pubchemQuery}
                onChange={(e) => setPubchemQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && runPubchem()}
                placeholder="Name or CID, e.g. \u201cferrocene\u201d"
                className="gt-input min-w-0 flex-1 text-sm"
              />
              <button onClick={runPubchem} disabled={loading} className="gt-btn-ghost px-3">
                <Search size={14} />
              </button>
            </div>
          </div>

          {demos.length > 0 && (
            <div className="gt-card p-4 sm:p-5">
              <label className="mb-2 block text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink-soft)]">
                Demo structures
              </label>
              <div className="flex flex-wrap gap-1.5">
                {demos.map((d) => (
                  <button key={d.key} onClick={() => loadDemo(d)} className="gt-chip">
                    {d.label}
                  </button>
                ))}
              </div>
            </div>
          )}

          {error && (
            <div className="gt-card-flat flex items-start gap-2 border-[var(--gt-ink)] p-3 text-xs" style={{ background: '#fdece7' }}>
              <AlertTriangle size={15} className="mt-0.5 shrink-0 text-[#c24a2e]" />
              <span className="text-[#7a2f1c]">{error}</span>
            </div>
          )}
        </div>

        {/* ---------------- results panel ---------------- */}
        <div className="space-y-5">
          <span className="gt-kicker text-[var(--gt-ink-soft)]"><span className="gt-kicker-num">03</span> Results</span>

          {!result && !loading && (
            <div className="flex h-full min-h-[280px] flex-col items-center justify-center rounded-[18px] border-2 border-dashed border-[var(--gt-ink)]/30 bg-[var(--gt-paper-soft)] p-8 text-center">
              <Orbit size={28} className="mb-2 text-[var(--gt-ink-soft)]" />
              <p className="text-sm text-[var(--gt-ink-soft)]">Paste a structure, pick a demo, or fetch one from PubChem to get started.</p>
            </div>
          )}

          {result && (
            <>
              <Reveal className="gt-card p-4 sm:p-5">
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div>
                    <div className="gt-heading text-3xl text-[var(--gt-teal)] sm:text-4xl">{result.groupPretty}</div>
                    <p className="mt-1 text-xs text-[var(--gt-ink-soft)]">
                      Detected automatically from {result.atomCount} atoms &middot; formula {result.formulaPretty}
                    </p>
                    {result.groupDescription && (
                      <p className="mt-2 max-w-xl text-[12px] leading-relaxed text-[var(--gt-ink)]/80">
                        {result.groupDescription}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    <button onClick={() => downloadSymmetryReport(result)} className="gt-btn-ghost">
                      <FileDown size={12} /> Export report
                    </button>
                    <button onClick={() => runAnalyze()} className="gt-btn-ghost">
                      <RotateCcw size={12} /> Re-run
                    </button>
                  </div>
                </div>

                <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">
                  <Stat label="Group order" value={result.orderLabel ? `${result.orderLabel} (infinite)` : `${result.detectedOps} / ${result.expectedOrder}`} />
                  <Stat label="Inversion" value={result.inversion ? 'Yes' : 'No'} />
                  <Stat label="Mirror planes" value={result.mirrorCount} />
                  <Stat label="Improper rot." value={result.improperRotationCount} />
                  <Stat label="Rotational orders" value={result.rotationalOrders?.join(', ') || 'none'} />
                  <Stat label="Linear" value={result.linear ? 'Yes' : 'No'} />
                  <Stat label="Tolerance" value={`${result.tolerance.toFixed(3)} \u00c5`} />
                  <Stat label="Max match error" value={`${result.maxError.toFixed(4)} \u00c5`} />
                  {typeof result.symmetryScore === 'number' && (
                    <Stat label="Symmetry score" value={`${result.symmetryScore}%`} />
                  )}
                </div>

                {result.distortionWarning && (
                  <div className="mt-3 flex items-start gap-2 rounded-lg border-2 border-[var(--gt-orange)]/50 p-2.5 text-[11px]" style={{ background: '#fdf1de' }}>
                    <AlertTriangle size={14} className="mt-0.5 shrink-0 text-[var(--gt-orange)]" />
                    <span className="text-[#6b4a13]">{result.distortionWarning}</span>
                  </div>
                )}
              </Reveal>

              {molBlock && (
                <Reveal delay={0.03} className="gt-card-flat gt-viewer-card overflow-hidden">
                  <div className="flex items-center gap-1.5 border-b-2 border-[var(--gt-ink)] px-4 py-2.5">
                    <Axis3d size={13} className="text-[var(--gt-teal)]" />
                    <span className="text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink-soft)]">
                      Live 3-D structure &mdash; the main event
                    </span>
                  </div>
                  <div className="p-1.5">
                    <SymmetryElementsViewer
                      molBlock={molBlock}
                      atoms={result.atoms}
                      center={result.center}
                      operations={result.operations}
                      groupPretty={result.groupPretty}
                      formulaPretty={result.formulaPretty}
                      height={480}
                      highlightLabel={activeHighlight}
                      onHighlightChange={setHoveredOp}
                      playRequest={playRequest}
                    />
                  </div>
                </Reveal>
              )}

              <Reveal delay={0.06} className="gt-card p-4 sm:p-5">
                <div className="mb-3 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink-soft)]">
                  <Axis3d size={13} /> Detected symmetry operations
                </div>
                <p className="mb-3 text-[11px] text-[var(--gt-ink-soft)]">
                  Hover an operation to spotlight its axis or plane above; click to play it out on the structure.
                </p>
                <div className="space-y-2">
                  {opGroups.map(([kind, labels]) => (
                    <div key={kind} className="flex flex-wrap items-center gap-1.5">
                      <span className="flex w-32 shrink-0 items-center gap-1.5 text-[11px] text-[var(--gt-ink-soft)]">
                        {KIND_META[kind] && (
                          <span className="h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: KIND_META[kind].color }} />
                        )}
                        {OP_KIND_LABEL[kind] || kind} ({labels.length})
                      </span>
                      <div className="flex flex-wrap gap-1">
                        {labels.slice(0, 24).map((l, i) => {
                          const isActive = activeHighlight === l;
                          return (
                            <button
                              key={i}
                              type="button"
                              onMouseEnter={() => setHoveredOp(l)}
                              onMouseLeave={() => setHoveredOp(null)}
                              onClick={() => {
                                setPinnedOp((p) => (p === l ? null : l));
                                setPlayRequest({ label: l, token: Date.now() });
                              }}
                              style={{ borderLeftColor: KIND_META[kind]?.color || undefined }}
                              className={`gt-op-btn ${isActive ? 'is-active' : ''}`}
                            >
                              {l}
                            </button>
                          );
                        })}
                        {labels.length > 24 && (
                          <span className="text-[10px] text-[var(--gt-ink-soft)]">+{labels.length - 24} more</span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </Reveal>

              {(result.decisionTrace?.length > 0 || result.rejectedTests?.length > 0) && (
                <Reveal delay={0.08} className="gt-card p-4 sm:p-5">
                  {result.decisionTrace?.length > 0 && (
                    <>
                      <div className="mb-3 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink-soft)]">
                        <ListTree size={13} /> Why this point group
                      </div>
                      <ol className="space-y-1.5 text-[12px] leading-relaxed text-[var(--gt-ink)]/85">
                        {result.decisionTrace.map((line, i) => (
                          <li key={i} className="flex gap-2">
                            <span className="shrink-0 font-mono text-[10px] text-[var(--gt-ink-soft)]">{i + 1}.</span>
                            <span>{line}</span>
                          </li>
                        ))}
                      </ol>
                    </>
                  )}

                  {result.rejectedTests?.length > 0 && (
                    <>
                      <div className={`${result.decisionTrace?.length ? 'mt-5 border-t-2 border-[var(--gt-ink)]/10 pt-4' : ''} mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink-soft)]`}>
                        <XCircle size={13} /> Symmetry tests that didn&rsquo;t pass
                      </div>
                      <p className="mb-2 text-[11px] text-[var(--gt-ink-soft)]">
                        Closest miss for each element that was tested but not found, sorted by how close it came.
                      </p>
                      <div className="flex flex-wrap gap-1.5">
                        {result.rejectedTests.map((t, i) => (
                          <span key={i} className="gt-op-btn" style={{ borderLeftColor: '#c24a2e', cursor: 'default' }}>
                            {t.label} <span className="text-[var(--gt-ink-soft)]">&mdash; off by {t.errorAngstrom} &Aring;</span>
                          </span>
                        ))}
                      </div>
                    </>
                  )}
                </Reveal>
              )}

              {result.representation ? (
                <Reveal delay={0.1} className="gt-card p-4 sm:p-5">
                  <div className="mb-3 text-xs font-semibold uppercase tracking-wide text-[var(--gt-teal)]">
                    Representation reduction
                  </div>
                  <div className="space-y-1 rounded-lg border-2 border-[var(--gt-ink)]/10 bg-[var(--gt-paper-soft)] p-3 font-mono text-[12px] text-[var(--gt-ink)]">
                    <div>&Gamma;<sub>3N</sub> = {result.representation.gamma3N}</div>
                    <div>&Gamma;<sub>trans</sub> = {result.representation.gammaTrans}</div>
                    <div>&Gamma;<sub>rot</sub> = {result.representation.gammaRot}</div>
                    <div className="text-[#b46a13] font-semibold">&Gamma;<sub>vib</sub> = {result.representation.gammaVib}</div>
                  </div>

                  <div className="mt-4 overflow-x-auto">
                    <table className="w-full min-w-[420px] text-left text-xs text-[var(--gt-ink)]">
                      <thead>
                        <tr className="text-[var(--gt-ink-soft)]">
                          <th className="py-1 pr-3 font-medium">Class</th>
                          <th className="py-1 pr-3 font-medium">Size</th>
                          <th className="py-1 pr-3 font-medium">&chi;(&Gamma;<sub>3N</sub>)</th>
                          {result.characterTable.irreps.map((ir) => (
                            <th key={ir.name} className="py-1 pr-3 font-medium">{ir.name}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {result.representation.classRows.map((row) => (
                          <tr key={row.label} className="border-t border-[var(--gt-ink)]/10">
                            <td className="py-1 pr-3 font-mono">{row.label}</td>
                            <td className="py-1 pr-3">{row.size}</td>
                            <td className="py-1 pr-3">{row.chiGamma3N}</td>
                            {row.characters.map((c, i) => (
                              <td key={i} className="py-1 pr-3">{c}</td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  {result.representation.note && (
                    <p className="mt-3 text-[11px] leading-relaxed text-[var(--gt-ink-soft)]">{result.representation.note}</p>
                  )}

                  {result.representation.validation && (
                    <div
                      className="mt-3 flex items-center gap-1.5 rounded-lg border-2 p-2 text-[11px]"
                      style={
                        result.representation.validation.gamma3NMatchesAtomCount && result.representation.validation.decompositionConsistent
                          ? { borderColor: 'rgba(15,157,138,0.3)', background: 'rgba(15,157,138,0.08)', color: '#0f6e5f' }
                          : { borderColor: 'rgba(194,74,46,0.4)', background: '#fdece7', color: '#7a2f1c' }
                      }
                    >
                      {result.representation.validation.gamma3NMatchesAtomCount && result.representation.validation.decompositionConsistent ? (
                        <>&#10003; Validated: &Gamma;<sub>3N</sub> accounts for exactly {result.representation.validation.gamma3NDimension} of {result.representation.validation.expectedDimension} Cartesian degrees of freedom (3N), and &Gamma;<sub>trans</sub>+&Gamma;<sub>rot</sub>+&Gamma;<sub>vib</sub> reconstructs it exactly.</>
                      ) : (
                        <>&#9888; Reduction mismatch: got {result.representation.validation.gamma3NDimension} of {result.representation.validation.expectedDimension} expected degrees of freedom &mdash; treat this vibrational breakdown with caution.</>
                      )}
                    </div>
                  )}

                  {result.representation.spectroscopy?.length > 0 && (
                    <div className="mt-4">
                      <div className="mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--gt-ink-soft)]">
                        <Radio size={13} /> IR / Raman activity
                      </div>
                      <div className="overflow-x-auto">
                        <table className="w-full min-w-[320px] text-left text-xs text-[var(--gt-ink)]">
                          <thead>
                            <tr className="text-[var(--gt-ink-soft)]">
                              <th className="py-1 pr-3 font-medium">Irrep</th>
                              <th className="py-1 pr-3 font-medium">Modes</th>
                              <th className="py-1 pr-3 font-medium">IR active</th>
                              <th className="py-1 pr-3 font-medium">Raman active</th>
                            </tr>
                          </thead>
                          <tbody>
                            {result.representation.spectroscopy.map((s) => (
                              <tr key={s.irrep} className="border-t border-[var(--gt-ink)]/10">
                                <td className="py-1 pr-3 font-mono">{s.irrep}</td>
                                <td className="py-1 pr-3">{s.count}</td>
                                <td className="py-1 pr-3">{s.irActive ? '\u2713' : '\u2014'}</td>
                                <td className="py-1 pr-3">
                                  {s.ramanActive ? '\u2713' : '\u2014'}
                                  {s.silent && <span className="ml-1 text-[10px] text-[var(--gt-ink-soft)]">(silent)</span>}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}

                  <button
                    onClick={() => setShowDerivation((s) => !s)}
                    className="mt-4 flex items-center gap-1 text-xs font-semibold text-[var(--gt-teal)] hover:underline"
                  >
                    <Info size={13} />
                    How this is derived
                    <ChevronDown size={13} className={`transition-transform ${showDerivation ? 'rotate-180' : ''}`} />
                  </button>
                  {showDerivation && (
                    <ol className="mt-3 space-y-2 text-[12px] leading-relaxed text-[var(--gt-ink-soft)]">
                      <li>
                        <b className="text-[var(--gt-ink)]">1. Build &Gamma;<sub>3N</sub>.</b> The 3N Cartesian
                        displacement coordinates are the basis. Only atoms an operation leaves in place
                        contribute: a proper rotation by &theta; contributes 1&nbsp;+&nbsp;2cos&theta; per
                        fixed atom, an improper operation contributes &minus;1&nbsp;+&nbsp;2cos&theta;.
                      </li>
                      <li>
                        <b className="text-[var(--gt-ink)]">2. Reduce it.</b> For each irreducible representation
                        &Gamma;<sub>i</sub>, the multiplicity is a<sub>i</sub> = (1/h) &sum;<sub>R</sub> n<sub>R</sub> &chi;<sub>3N</sub>(R) &chi;<sub>i</sub>(R),
                        with h the group order and n<sub>R</sub> the class size.
                      </li>
                      <li>
                        <b className="text-[var(--gt-ink)]">3. Strip translation and rotation.</b> &Gamma;<sub>vib</sub> = &Gamma;<sub>3N</sub> &minus; &Gamma;<sub>trans</sub> &minus; &Gamma;<sub>rot</sub>,
                        using the x/y/z and R<sub>x</sub>/R<sub>y</sub>/R<sub>z</sub> basis functions from the character table.
                      </li>
                      <li>
                        <b className="text-[var(--gt-ink)]">4. The point group itself</b> comes first and
                        separately &mdash; from the actual operations discovered on this geometry (their
                        closure, then grouped into conjugacy classes), not from this table.
                      </li>
                    </ol>
                  )}
                </Reveal>
              ) : (
                <div className="gt-card-flat flex items-start gap-2 p-3 text-xs" style={{ background: '#fdf1de' }}>
                  <AlertTriangle size={15} className="mt-0.5 shrink-0 text-[var(--gt-orange)]" />
                  <span className="text-[#6b4a13]">
                    {result.representationError
                      ? `Point group found, but the representation reduction couldn't be completed: ${result.representationError}`
                      : `A character table for ${result.groupPretty} isn't in this build yet, so the point group is shown above but the \u0393 reduction isn't.`}
                  </span>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
    </div>
  );
}

function Stat({ label, value }) {
  return (
    <div className="gt-stat">
      <div className="text-[10px] uppercase tracking-wide text-[var(--gt-ink-soft)]">{label}</div>
      <div className="mt-0.5 font-mono text-sm text-[var(--gt-ink)]">{value}</div>
    </div>
  );
}

/** Hero graphic — a big sky-blue block with a rotating symmetry-axis ring
 *  and an orbiting "electron" dot, echoing the page's search/inspection
 *  theme without depending on the app's dark 3-D viewer or its neon
 *  QuantumOrbitAnimation. Pure SVG + CSS, self-contained to this page. */
function GTHeroGraphic() {
  return (
    <div
      className="relative flex aspect-square w-full max-w-[280px] items-center justify-center overflow-hidden rounded-[26px] border-2 border-[var(--gt-ink)] ml-auto"
      style={{ background: 'var(--gt-sky)', boxShadow: '8px 8px 0 var(--gt-ink)' }}
    >
      <div
        className="pointer-events-none absolute inset-0 opacity-25"
        style={{ backgroundImage: 'radial-gradient(circle at 1px 1px, white 1.5px, transparent 0)', backgroundSize: '20px 20px' }}
      />
      <svg viewBox="0 0 200 200" className="relative z-10 h-4/5 w-4/5">
        <g className="gt-hero-shape" style={{ transformOrigin: '100px 100px' }}>
          <circle cx="100" cy="100" r="70" fill="none" stroke="#fff" strokeWidth="10" />
          <ellipse cx="100" cy="100" rx="70" ry="26" fill="none" stroke="#16191b" strokeWidth="3" opacity="0.35" />
        </g>
        <circle cx="100" cy="100" r="16" fill="#16191b" />
        <circle cx="100" cy="100" r="7" fill="var(--gt-orange)" />
        <circle className="gt-hero-dot" cx="170" cy="100" r="8" fill="#16191b" />
      </svg>
    </div>
  );
}