// frontend/src/lib/functionalGroups.js

// Functional Group Library data (blueprint item 10). Each group is a small,
// illustrative molecular graph — same atoms/bonds shape used everywhere else
// in the app, so it can be dropped straight into the Draw Lab. "R" is used
// as a placeholder substituent atom (a generic gray node, not a real element)
// to represent "the rest of the molecule."
//
// `tier` distinguishes the standard undergraduate organic chemistry set
// ('core') from more specialized/advanced groups ('advanced') that show up
// in second-year+ courses or specific subfields. Defaults to 'core' so
// existing entries don't need to be touched.

function buildGroup({ name, formula, description, recognition, examples, atomSpecs, bondSpecs, tier }) {
  const atoms = atomSpecs.map((spec, i) => ({
    id: `a${i}`,
    element: spec.element,
    x: spec.dx,
    y: spec.dy,
    charge: spec.charge || 0,
    lonePairs: spec.lonePairs || 0,
  }));
  const bonds = bondSpecs.map((spec, i) => ({
    id: `b${i}`,
    from: `a${spec.from}`,
    to: `a${spec.to}`,
    order: spec.order || 1,
    aromatic: spec.aromatic || false,
  }));
  return {
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    name,
    formula,
    description,
    recognition,
    examples,
    tier: tier || 'core',
    structure_2d: { atoms, bonds },
  };
}

export const FUNCTIONAL_GROUPS = [
  buildGroup({
    name: 'Alcohol',
    formula: 'R–OH',
    description: 'A hydroxyl group (–OH) bonded to a carbon chain. Polar, capable of hydrogen bonding, and generally more water-soluble and higher-boiling than the corresponding hydrocarbon.',
    recognition: 'Look for a single-bonded O–H hanging off a carbon skeleton (not on a carbonyl carbon — that would be a carboxylic acid instead).',
    examples: 'Ethanol, isopropyl alcohol, cholesterol',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'O', dx: 50, dy: 0 },
      { element: 'H', dx: 90, dy: -25 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }],
  }),
  buildGroup({
    name: 'Ether',
    formula: 'R–O–R′',
    description: 'An oxygen atom bonded to two carbon groups, with no O–H. Relatively unreactive; often used as solvents.',
    recognition: 'An oxygen sandwiched between two carbons, both single bonds, no hydrogen on the oxygen.',
    examples: 'Diethyl ether, THF (tetrahydrofuran)',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'O', dx: 50, dy: 0 },
      { element: 'R', dx: 100, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }],
  }),
  buildGroup({
    name: 'Aldehyde',
    formula: 'R–CHO',
    description: 'A carbonyl (C=O) at the end of a carbon chain, with one hydrogen directly on that carbon. More reactive toward oxidation than ketones.',
    recognition: 'A C=O where the carbonyl carbon also carries exactly one H and one R group (never two R groups — that would be a ketone).',
    examples: 'Formaldehyde, acetaldehyde, vanillin',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'O', dx: 85, dy: -35 },
      { element: 'H', dx: 50, dy: 40 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }],
  }),
  buildGroup({
    name: 'Ketone',
    formula: 'R–CO–R′',
    description: 'A carbonyl (C=O) flanked by two carbon groups. More resistant to oxidation than aldehydes since there\'s no C–H on the carbonyl carbon.',
    recognition: 'A C=O in the middle of a chain, with carbons (not H) on both sides of the carbonyl carbon.',
    examples: 'Acetone, butanone (MEK)',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'O', dx: 50, dy: -42 },
      { element: 'R', dx: 100, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }],
  }),
  buildGroup({
    name: 'Carboxylic Acid',
    formula: 'R–COOH',
    description: 'A carbonyl and a hydroxyl on the same carbon (–COOH). Acidic — readily donates the O–H proton, especially in water.',
    recognition: 'C=O and C–O–H both attached to the same carbon.',
    examples: 'Acetic acid, citric acid, amino acids',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'O', dx: 85, dy: -35 },
      { element: 'O', dx: 50, dy: 45 },
      { element: 'H', dx: 90, dy: 70 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }, { from: 3, to: 4 }],
  }),
  buildGroup({
    name: 'Ester',
    formula: 'R–CO–O–R′',
    description: 'A carbonyl next to a single-bonded oxygen that connects to another carbon group. Often responsible for pleasant fruity smells.',
    recognition: 'C=O directly bonded to an –O–R (as opposed to –O–H, which would make it a carboxylic acid).',
    examples: 'Ethyl acetate, fats and oils (triglycerides)',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'O', dx: 50, dy: -42 },
      { element: 'O', dx: 92, dy: 25 },
      { element: 'R', dx: 135, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }, { from: 3, to: 4 }],
  }),
  buildGroup({
    name: 'Amide',
    formula: 'R–CO–NH₂',
    description: 'A carbonyl bonded to a nitrogen. The backbone linkage of proteins (where it\'s called a peptide bond).',
    recognition: 'C=O directly bonded to nitrogen, distinguishing it from an amine (no carbonyl) or ester (oxygen instead of nitrogen).',
    examples: 'Acetamide, the peptide bonds in proteins',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'O', dx: 50, dy: -42 },
      { element: 'N', dx: 92, dy: 25 },
      { element: 'H', dx: 130, dy: 5 },
      { element: 'H', dx: 92, dy: 65 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 },
      { from: 3, to: 4 }, { from: 3, to: 5 },
    ],
  }),
  buildGroup({
    name: 'Amine',
    formula: 'R–NH₂',
    description: 'A nitrogen bonded to one or more carbon groups, with a lone pair making it basic — amines readily accept a proton.',
    recognition: 'Nitrogen with single bonds only, no adjacent carbonyl (that combination would make it an amide instead).',
    examples: 'Methylamine, histamine, many alkaloids',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'N', dx: 50, dy: 0, lonePairs: 1 },
      { element: 'H', dx: 85, dy: -25 },
      { element: 'H', dx: 85, dy: 25 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }, { from: 1, to: 3 }],
  }),
  buildGroup({
    name: 'Nitrile',
    formula: 'R–C≡N',
    description: 'A carbon triple-bonded to nitrogen. Linear at that carbon, polar, and a common precursor in organic synthesis.',
    recognition: 'A triple bond ending in nitrogen — visually similar to an alkyne but one end is N, not C.',
    examples: 'Acetonitrile, acrylonitrile',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'N', dx: 95, dy: 0, lonePairs: 1 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 3 }],
  }),
  buildGroup({
    name: 'Nitro',
    formula: 'R–NO₂',
    description: 'A nitrogen bonded to two oxygens, typically drawn with one N=O and one N–O⁻, with the nitrogen carrying a +1 formal charge overall. Strongly electron-withdrawing.',
    recognition: 'A nitrogen with two oxygens attached and no hydrogens on the nitrogen itself.',
    examples: 'Nitrobenzene, TNT, nitroglycerin',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'N', dx: 50, dy: 0, charge: 1 },
      { element: 'O', dx: 85, dy: -35, charge: 0 },
      { element: 'O', dx: 85, dy: 35, charge: -1, lonePairs: 3 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }],
  }),
  buildGroup({
    name: 'Alkene',
    formula: 'R₂C=CR₂',
    description: 'A carbon–carbon double bond. Planar around the double bond, and reactive toward addition reactions (e.g. with H₂, Br₂, HX).',
    recognition: 'Two carbons joined by a double bond, each also bonded to other groups.',
    examples: 'Ethylene, propene, unsaturated fats',
    atomSpecs: [
      { element: 'R', dx: -40, dy: -20 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'R', dx: 90, dy: -20 },
      { element: 'R', dx: -40, dy: 25 },
      { element: 'R', dx: 90, dy: 25 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3 },
      { from: 1, to: 4 }, { from: 2, to: 5 },
    ],
  }),
  buildGroup({
    name: 'Alkyne',
    formula: 'R–C≡C–R′',
    description: 'A carbon–carbon triple bond. Linear geometry at both carbons, and even more reactive than alkenes toward addition.',
    recognition: 'Two carbons joined by a triple bond, each bonded to just one other group (since a triple bond uses up the rest of the valence).',
    examples: 'Acetylene, propyne',
    atomSpecs: [
      { element: 'R', dx: -40, dy: 0 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'R', dx: 90, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 3 }, { from: 2, to: 3 }],
  }),
  buildGroup({
    name: 'Aromatic Ring',
    formula: 'C₆H₆ (as substituent: C₆H₅–)',
    description: 'A six-membered ring of alternating double bonds (drawn here as the classic Kekulé structure), delocalized in reality across the whole ring. Unusually stable due to this delocalization (aromaticity/resonance).',
    recognition: 'A hexagon of carbons with alternating single/double bonds — real electron density is spread evenly around the ring, not truly alternating.',
    examples: 'Benzene, toluene, phenol, aspirin\'s ring',
    atomSpecs: [
      { element: 'C', dx: 0, dy: -46 },
      { element: 'C', dx: 40, dy: -23 },
      { element: 'C', dx: 40, dy: 23 },
      { element: 'C', dx: 0, dy: 46 },
      { element: 'C', dx: -40, dy: 23 },
      { element: 'C', dx: -40, dy: -23 },
    ],
    bondSpecs: [
      { from: 0, to: 1, order: 2, aromatic: true }, { from: 1, to: 2, order: 1, aromatic: true },
      { from: 2, to: 3, order: 2, aromatic: true }, { from: 3, to: 4, order: 1, aromatic: true },
      { from: 4, to: 5, order: 2, aromatic: true }, { from: 5, to: 0, order: 1, aromatic: true },
    ],
  }),
  buildGroup({
    name: 'Halide',
    formula: 'R–X',
    description: 'A halogen (F, Cl, Br, or I) bonded to a carbon. Polar C–X bond makes these good leaving groups in substitution reactions.',
    recognition: 'Any single-bonded halogen hanging off a carbon skeleton.',
    examples: 'Chloroform, chlorofluorocarbons (CFCs), vinyl chloride',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'Cl', dx: 50, dy: 0, lonePairs: 3 },
    ],
    bondSpecs: [{ from: 0, to: 1 }],
  }),
  buildGroup({
    name: 'Thiol',
    formula: 'R–SH',
    description: 'Sulfur\'s analog of an alcohol (–SH instead of –OH). Weaker H-bonding than –OH but far more nucleophilic, and notorious for pungent smells even in tiny amounts.',
    recognition: 'A single-bonded S–H hanging off a carbon skeleton — same shape as an alcohol but sulfur instead of oxygen.',
    examples: 'Ethanethiol (added to natural gas for odor), cysteine\'s side chain',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'S', dx: 50, dy: 0, lonePairs: 2 },
      { element: 'H', dx: 90, dy: -25 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }],
  }),
  buildGroup({
    name: 'Thioether (Sulfide)',
    formula: 'R–S–R′',
    description: 'Sulfur\'s analog of an ether — a sulfur bonded to two carbon groups with no S–H. More nucleophilic and more easily oxidized than ethers.',
    recognition: 'A sulfur sandwiched between two carbons, both single bonds, no hydrogen on the sulfur.',
    examples: 'Dimethyl sulfide, methionine\'s side chain',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'S', dx: 50, dy: 0, lonePairs: 2 },
      { element: 'R', dx: 100, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }],
  }),
  buildGroup({
    name: 'Disulfide',
    formula: 'R–S–S–R′',
    description: 'Two sulfurs single-bonded to each other, each also bonded to a carbon group. The S–S bond is redox-active — easily broken (reduced) and reformed (oxidized).',
    recognition: 'Two adjacent sulfurs in a chain, each with exactly one other bond besides the S–S bond.',
    examples: 'Cystine (the disulfide-linked form of cysteine), the bonds that set curly hair perms',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'S', dx: 45, dy: 0, lonePairs: 2 },
      { element: 'S', dx: 90, dy: 0, lonePairs: 2 },
      { element: 'R', dx: 135, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }, { from: 2, to: 3 }],
  }),
  buildGroup({
    name: 'Sulfoxide',
    formula: 'R–SO–R′',
    description: 'A sulfur double-bonded to one oxygen and single-bonded to two carbon groups, with a lone pair making the sulfur a stereocenter. A common step on the way to a sulfone.',
    recognition: 'One S=O flanked by two carbon groups — like a ketone\'s shape but with sulfur instead of carbon at the center, and only one oxygen.',
    examples: 'DMSO (dimethyl sulfoxide), a common polar aprotic solvent',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'S', dx: 50, dy: 0, lonePairs: 1 },
      { element: 'O', dx: 50, dy: -42 },
      { element: 'R', dx: 100, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }],
  }),
  buildGroup({
    name: 'Sulfone',
    formula: 'R–SO₂–R′',
    description: 'A sulfur double-bonded to two oxygens and single-bonded to two carbon groups. Strongly electron-withdrawing and chemically robust.',
    recognition: 'A sulfur with two S=O double bonds and two carbon groups attached — no OH anywhere (that combination would be a sulfonic acid instead).',
    examples: 'Sulfolane (a solvent), sulfone-based drugs like dapsone',
    atomSpecs: [
      { element: 'R', dx: -45, dy: 0 },
      { element: 'S', dx: 0, dy: 0 },
      { element: 'O', dx: 0, dy: -45 },
      { element: 'O', dx: 0, dy: 45 },
      { element: 'R', dx: 45, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3, order: 2 }, { from: 1, to: 4 }],
  }),
  buildGroup({
    name: 'Sulfonic Acid',
    formula: 'R–SO₃H',
    description: 'A sulfur with two S=O double bonds and one S–OH, bonded to a carbon group. A very strong acid — one of the strongest common organic acid groups.',
    recognition: 'Two S=O double bonds plus a single-bonded O–H, all on the same sulfur.',
    examples: 'Sulfanilic acid, the sulfonic acid groups in detergents and dyes',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'S', dx: 50, dy: 0 },
      { element: 'O', dx: 30, dy: -45 },
      { element: 'O', dx: 70, dy: -45 },
      { element: 'O', dx: 50, dy: 45 },
      { element: 'H', dx: 90, dy: 65 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3, order: 2 },
      { from: 1, to: 4 }, { from: 4, to: 5 },
    ],
  }),
  buildGroup({
    name: 'Sulfonamide',
    formula: 'R–SO₂–NH₂',
    description: 'A sulfone-like S(=O)₂ bonded to nitrogen instead of a second carbon. The core of an entire class of antibacterial drugs ("sulfa drugs").',
    recognition: 'Two S=O double bonds on a sulfur that\'s also bonded to nitrogen — the sulfur analog of an amide.',
    examples: 'Sulfanilamide and related sulfa antibiotics',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'S', dx: 50, dy: 0 },
      { element: 'O', dx: 30, dy: -45 },
      { element: 'O', dx: 70, dy: -45 },
      { element: 'N', dx: 50, dy: 45 },
      { element: 'H', dx: 85, dy: 65 },
      { element: 'H', dx: 50, dy: 85 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3, order: 2 },
      { from: 1, to: 4 }, { from: 4, to: 5 }, { from: 4, to: 6 },
    ],
  }),
  buildGroup({
    name: 'Acyl Halide',
    formula: 'R–CO–X',
    description: 'A carbonyl bonded directly to a halogen (usually Cl). Extremely reactive — readily attacked by water, alcohols, and amines, making it a fast way to build esters and amides.',
    recognition: 'C=O with a halogen directly on the carbonyl carbon, in place of the OH, OR, or N of an acid, ester, or amide.',
    examples: 'Acetyl chloride, benzoyl chloride',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'O', dx: 50, dy: -42 },
      { element: 'Cl', dx: 95, dy: 25, lonePairs: 3 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }],
  }),
  buildGroup({
    name: 'Anhydride',
    formula: 'R–CO–O–CO–R′',
    description: 'Two carbonyls linked through a shared oxygen — essentially two carboxylic acids condensed with loss of water. Reactive, though less so than an acyl halide.',
    recognition: 'Two C=O groups both bonded to the same central oxygen, with no hydrogen on that oxygen.',
    examples: 'Acetic anhydride, the anhydride linkages formed during peptide/ester synthesis',
    atomSpecs: [
      { element: 'R', dx: -90, dy: -20 },
      { element: 'C', dx: -45, dy: 0 },
      { element: 'O', dx: -45, dy: -42 },
      { element: 'O', dx: 0, dy: 25 },
      { element: 'C', dx: 45, dy: 0 },
      { element: 'O', dx: 45, dy: -42 },
      { element: 'R', dx: 90, dy: -20 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 },
      { from: 3, to: 4 }, { from: 4, to: 5, order: 2 }, { from: 4, to: 6 },
    ],
  }),
  buildGroup({
    name: 'Imine',
    formula: 'R₂C=N–R′',
    description: 'A carbon–nitrogen double bond (also called a Schiff base). Commonly formed when an amine condenses with an aldehyde or ketone, and a key intermediate in reductive amination.',
    recognition: 'A C=N double bond — same shape as an alkene, but with nitrogen (carrying a lone pair) at one end instead of carbon.',
    examples: 'Retinal-opsin Schiff base in vision, imines formed en route to reductive amination products',
    atomSpecs: [
      { element: 'R', dx: -40, dy: -20 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'N', dx: 50, dy: 0, lonePairs: 1 },
      { element: 'R', dx: 90, dy: -20 },
      { element: 'R', dx: -40, dy: 25 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3 }, { from: 1, to: 4 },
    ],
  }),
  buildGroup({
    name: 'Epoxide',
    formula: 'C₂H₄O (strained triangular ring)',
    description: 'A three-membered ring containing an oxygen. The tight ring angles create enormous ring strain, making epoxides far more reactive toward ring-opening than a normal ether.',
    recognition: 'A small triangle: two carbons bonded to each other and each bonded to the same oxygen.',
    examples: 'Ethylene oxide, epoxide intermediates in steroid and terpene biosynthesis',
    atomSpecs: [
      { element: 'C', dx: -25, dy: 0 },
      { element: 'C', dx: 25, dy: 0 },
      { element: 'O', dx: 0, dy: -40, lonePairs: 2 },
      { element: 'R', dx: -50, dy: 25 },
      { element: 'R', dx: 50, dy: 25 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 0, to: 2 }, { from: 1, to: 2 }, { from: 0, to: 3 }, { from: 1, to: 4 },
    ],
  }),
  buildGroup({
    name: 'Enol',
    formula: 'R–C(OH)=CR₂',
    description: 'A hydroxyl group directly on a double-bonded carbon. Usually the minor, higher-energy tautomer that interconverts with the corresponding ketone or aldehyde.',
    recognition: 'An –OH attached straight to one of the two carbons of a C=C double bond, rather than to an sp3 carbon.',
    examples: 'The enol tautomer of acetone (present in tiny equilibrium amounts), vitamin C\'s enediol group',
    atomSpecs: [
      { element: 'R', dx: -40, dy: -20 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'C', dx: 50, dy: 0 },
      { element: 'O', dx: 50, dy: -42 },
      { element: 'H', dx: 85, dy: -62 },
      { element: 'R', dx: -40, dy: 25 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3 }, { from: 3, to: 4 }, { from: 1, to: 5 },
    ],
  }),
  buildGroup({
    name: 'Azide',
    formula: 'R–N₃',
    description: 'A chain of three nitrogens bonded to a carbon group, best represented as a resonance hybrid with charge spread across the terminal nitrogens. Widely used in "click chemistry" and as an explosive/energetic group.',
    recognition: 'Three nitrogens in a row hanging off a carbon, with the middle nitrogen usually drawn with a formal +1 charge.',
    examples: 'Sodium azide (airbag propellant), azide handles used in bioorthogonal click chemistry',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'N', dx: 45, dy: 0 },
      { element: 'N', dx: 85, dy: 0, charge: 1 },
      { element: 'N', dx: 125, dy: 0, charge: -1, lonePairs: 3 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3, order: 2 }],
  }),
  buildGroup({
    name: 'Isocyanate',
    formula: 'R–N=C=O',
    description: 'A nitrogen double-bonded to a carbon that\'s also double-bonded to oxygen — a cumulated diene-like system. Highly electrophilic; reacts readily with alcohols and amines to form carbamates and ureas.',
    recognition: 'Two consecutive double bonds, N=C=O, all in a line — distinct from a nitrile (single N at the end) or an amide (only one double bond, to O).',
    examples: 'Methyl isocyanate, the isocyanates used to make polyurethane foams',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'N', dx: 45, dy: 0, lonePairs: 1 },
      { element: 'C', dx: 85, dy: 0 },
      { element: 'O', dx: 125, dy: 0 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3, order: 2 }],
  }),
  buildGroup({
    name: 'Carbamate',
    formula: 'R–O–CO–NH–R′',
    description: 'A hybrid of an ester and an amide — a carbonyl flanked by an oxygen on one side and a nitrogen on the other. More stable than either a simple ester or a simple imine, which is why it shows up in protecting groups and drug design.',
    recognition: 'A carbonyl carbon bonded to both an –O–R and an –N(H)–R, rather than two of the same kind (that would make it an ester, anhydride, or amide instead).',
    examples: 'Boc/Cbz protecting groups in peptide synthesis, carbamate-based pesticides',
    atomSpecs: [
      { element: 'R', dx: -45, dy: -20 },
      { element: 'O', dx: 0, dy: 0 },
      { element: 'C', dx: 45, dy: 0 },
      { element: 'O', dx: 45, dy: -42 },
      { element: 'N', dx: 90, dy: 25 },
      { element: 'H', dx: 125, dy: 5 },
      { element: 'R', dx: 90, dy: 65 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2 }, { from: 2, to: 3, order: 2 },
      { from: 2, to: 4 }, { from: 4, to: 5 }, { from: 4, to: 6 },
    ],
  }),
  buildGroup({
    name: 'Imide',
    formula: 'R–CO–NH–CO–R′',
    description: 'Two carbonyls flanking a single nitrogen — the nitrogen analog of an anhydride. More electron-poor and hydrolytically stable than a simple amide.',
    recognition: 'Two C=O groups both bonded to the same nitrogen, with one N–H remaining.',
    examples: 'The imide ring in phthalimide (used in the Gabriel synthesis), succinimide',
    atomSpecs: [
      { element: 'R', dx: -90, dy: -20 },
      { element: 'C', dx: -45, dy: 0 },
      { element: 'O', dx: -45, dy: -42 },
      { element: 'N', dx: 0, dy: 25 },
      { element: 'H', dx: 0, dy: 65 },
      { element: 'C', dx: 45, dy: 0 },
      { element: 'O', dx: 45, dy: -42 },
      { element: 'R', dx: 90, dy: -20 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 1, to: 3 }, { from: 3, to: 4 },
      { from: 3, to: 5 }, { from: 5, to: 6, order: 2 }, { from: 5, to: 7 },
    ],
  }),
  buildGroup({
    name: 'Phosphate Ester',
    formula: 'R–O–PO(OH)₂',
    description: 'A phosphorus bonded to one oxygen by a double bond and to three other oxygens by single bonds, one of which links to a carbon group. The backbone linkage of DNA/RNA and the core of ATP\'s energy-carrying bonds.',
    recognition: 'A central phosphorus with one P=O, one P–O–R (bridging to carbon), and one or two P–OH groups.',
    examples: 'The sugar-phosphate backbone of DNA and RNA, ATP\'s phosphate groups',
    atomSpecs: [
      { element: 'R', dx: -45, dy: 0 },
      { element: 'O', dx: 0, dy: 0 },
      { element: 'P', dx: 45, dy: 0 },
      { element: 'O', dx: 45, dy: -45 },
      { element: 'O', dx: 85, dy: 25 },
      { element: 'H', dx: 120, dy: 10 },
      { element: 'O', dx: 45, dy: 50 },
      { element: 'H', dx: 80, dy: 70 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2 }, { from: 2, to: 3, order: 2 },
      { from: 2, to: 4 }, { from: 4, to: 5 }, { from: 2, to: 6 }, { from: 6, to: 7 },
    ],
  }),
  buildGroup({
    name: 'Quaternary Ammonium',
    formula: 'R₄N⁺',
    description: 'A nitrogen bonded to four carbon groups, permanently positively charged (no lone pair left to be protonated or deprotonated away). Unlike regular amines, its charge doesn\'t depend on pH.',
    recognition: 'A nitrogen with four single bonds to carbon and a formal +1 charge — no N–H, no lone pair.',
    examples: 'Choline, quaternary ammonium disinfectants ("quats"), acetylcholine',
    atomSpecs: [
      { element: 'N', dx: 0, dy: 0, charge: 1 },
      { element: 'R', dx: -40, dy: -30 },
      { element: 'R', dx: 40, dy: -30 },
      { element: 'R', dx: -40, dy: 30 },
      { element: 'R', dx: 40, dy: 30 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 0, to: 2 }, { from: 0, to: 3 }, { from: 0, to: 4 }],
  }),

  // ---- Advanced / specialized groups (tier: 'advanced') ----
  // Beyond a standard intro/intermediate organic course — second-year
  // topics, named-reaction intermediates, or specific subfields
  // (organometallic, organoboron, organosilicon chemistry).
  buildGroup({
    name: 'Oxime',
    formula: 'R₂C=N–OH',
    tier: 'advanced',
    description: 'A carbon–nitrogen double bond where the nitrogen also carries a hydroxyl. Formed from the condensation of an aldehyde or ketone with hydroxylamine.',
    recognition: 'A C=N with an –OH on the nitrogen — distinguishes it from a plain imine, which has an R group (or H) on the nitrogen instead.',
    examples: 'Acetone oxime, oximes used as antidotes for nerve-agent poisoning (e.g. pralidoxime)',
    atomSpecs: [
      { element: 'R', dx: -40, dy: -20 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'N', dx: 50, dy: 0, lonePairs: 1 },
      { element: 'O', dx: 90, dy: -25 },
      { element: 'H', dx: 125, dy: -45 },
      { element: 'R', dx: -40, dy: 25 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3 }, { from: 3, to: 4 }, { from: 1, to: 5 },
    ],
  }),
  buildGroup({
    name: 'Hydrazone',
    formula: 'R₂C=N–NH₂',
    tier: 'advanced',
    description: 'A carbon–nitrogen double bond where the nitrogen carries an –NH₂ instead of an –OH. Formed from condensing an aldehyde/ketone with hydrazine, and the key intermediate in the Wolff–Kishner reduction.',
    recognition: 'A C=N with a second nitrogen (bearing two hydrogens) attached to the first — the nitrogen analog of an oxime.',
    examples: 'Phenylhydrazones (classic carbonyl-identification derivatives), the hydrazone intermediate in Wolff–Kishner reduction',
    atomSpecs: [
      { element: 'R', dx: -40, dy: -20 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'N', dx: 50, dy: 0, lonePairs: 1 },
      { element: 'N', dx: 90, dy: 25 },
      { element: 'H', dx: 125, dy: 5 },
      { element: 'H', dx: 90, dy: 65 },
      { element: 'R', dx: -40, dy: 25 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3 },
      { from: 3, to: 4 }, { from: 3, to: 5 }, { from: 1, to: 6 },
    ],
  }),
  buildGroup({
    name: 'Diazo Compound',
    formula: 'R₂C=N₂',
    tier: 'advanced',
    description: 'A carbon double-bonded to a terminal nitrogen–nitrogen unit, with the charge best drawn as +1 on the inner nitrogen and −1 on the outer one. Highly reactive carbene precursors.',
    recognition: 'A carbon with two N=N-style double bonds trailing off it, carrying formal + and − charges on the nitrogens — not to be confused with an azide, where the chain hangs off nitrogen rather than carbon.',
    examples: 'Diazomethane (a classic methylating agent), diazo reagents used in carbene-transfer reactions',
    atomSpecs: [
      { element: 'R', dx: -40, dy: -20 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'N', dx: 45, dy: 0, charge: 1 },
      { element: 'N', dx: 85, dy: 0, charge: -1, lonePairs: 3 },
      { element: 'R', dx: -40, dy: 25 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3, order: 2 }, { from: 1, to: 4 }],
  }),
  buildGroup({
    name: 'Phosphorus Ylide',
    formula: 'R₃P=CR₂',
    tier: 'advanced',
    description: 'A phosphorus bonded to three carbon groups and double-bonded to a carbanion-like carbon. The reactive species in the Wittig reaction, used to convert ketones/aldehydes directly into alkenes.',
    recognition: 'A phosphorus with three single-bonded R groups plus one P=C double bond to a carbon that itself carries a negative-charge-like lone pair.',
    examples: 'The ylide reagent in the Wittig olefination',
    atomSpecs: [
      { element: 'R', dx: -50, dy: -35 },
      { element: 'R', dx: -50, dy: 0 },
      { element: 'R', dx: -50, dy: 35 },
      { element: 'P', dx: 0, dy: 0 },
      { element: 'C', dx: 45, dy: 0, charge: -1, lonePairs: 1 },
      { element: 'R', dx: 80, dy: -25 },
      { element: 'R', dx: 80, dy: 25 },
    ],
    bondSpecs: [
      { from: 0, to: 3 }, { from: 1, to: 3 }, { from: 2, to: 3 },
      { from: 3, to: 4, order: 2 }, { from: 4, to: 5 }, { from: 4, to: 6 },
    ],
  }),
  buildGroup({
    name: 'Boronic Acid',
    formula: 'R–B(OH)₂',
    tier: 'advanced',
    description: 'A boron bonded to a carbon group and two hydroxyls. Electron-deficient (boron has only 6 valence electrons here), which is exactly what makes it useful as a coupling partner in Suzuki reactions.',
    recognition: 'A boron with one carbon group and two –OH groups — no double bonds, since boron in this form is trivalent and electron-deficient.',
    examples: 'Phenylboronic acid, boronic acid coupling partners in Suzuki–Miyaura cross-coupling',
    atomSpecs: [
      { element: 'R', dx: 0, dy: 0 },
      { element: 'B', dx: 45, dy: 0 },
      { element: 'O', dx: 80, dy: -30 },
      { element: 'H', dx: 115, dy: -50 },
      { element: 'O', dx: 45, dy: 45 },
      { element: 'H', dx: 80, dy: 65 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }, { from: 2, to: 3 }, { from: 1, to: 4 }, { from: 4, to: 5 }],
  }),
  buildGroup({
    name: 'Silyl Ether',
    formula: 'R–O–SiR₃',
    tier: 'advanced',
    description: 'An oxygen bonded to a carbon on one side and a silicon (carrying three more R groups, often methyl) on the other. Essentially a bulky, robust protecting group for alcohols.',
    recognition: 'An ether-like oxygen where one side is silicon instead of carbon, and that silicon carries three additional R groups.',
    examples: 'TMS ethers, TBS-protected alcohols in multi-step synthesis',
    atomSpecs: [
      { element: 'R', dx: -45, dy: 0 },
      { element: 'O', dx: 0, dy: 0 },
      { element: 'Si', dx: 45, dy: 0 },
      { element: 'R', dx: 85, dy: -30 },
      { element: 'R', dx: 85, dy: 0 },
      { element: 'R', dx: 85, dy: 30 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2 }, { from: 2, to: 3 }, { from: 2, to: 4 }, { from: 2, to: 5 }],
  }),
  buildGroup({
    name: 'Orthoester',
    formula: 'RC(OR′)₃',
    tier: 'advanced',
    description: 'A carbon bonded to three separate alkoxy (–OR) groups — essentially a carboxylic acid derivative taken one oxidation step further than an ester. Hydrolyzes readily back to an ester or acid.',
    recognition: 'A single central carbon bonded to three different oxygens, each of which continues on to another carbon group — three "ester-like" oxygens on one carbon, not just one.',
    examples: 'Trimethyl orthoformate, orthoester protecting groups used in carbohydrate and nucleotide synthesis',
    atomSpecs: [
      { element: 'C', dx: 0, dy: 0 },
      { element: 'R', dx: -45, dy: 0 },
      { element: 'O', dx: 30, dy: -40 },
      { element: 'R', dx: 65, dy: -60 },
      { element: 'O', dx: 45, dy: 10 },
      { element: 'R', dx: 90, dy: 30 },
      { element: 'O', dx: 0, dy: 45 },
      { element: 'R', dx: -35, dy: 80 },
    ],
    bondSpecs: [
      { from: 0, to: 1 }, { from: 0, to: 2 }, { from: 2, to: 3 },
      { from: 0, to: 4 }, { from: 4, to: 5 }, { from: 0, to: 6 }, { from: 6, to: 7 },
    ],
  }),
  buildGroup({
    name: 'Ketene',
    formula: 'R₂C=C=O',
    tier: 'advanced',
    description: 'A carbon double-bonded both to another carbon and, through that carbon, to oxygen — a cumulated system like isocyanate but all-carbon-and-oxygen. Highly reactive and a useful reagent for adding acetyl groups.',
    recognition: 'Two consecutive double bonds, C=C=O, ending in oxygen — visually like an isocyanate but with carbon instead of nitrogen in the middle position\'s neighbor.',
    examples: 'Ketene itself (H₂C=C=O), used industrially to make acetic anhydride',
    atomSpecs: [
      { element: 'R', dx: -40, dy: -20 },
      { element: 'C', dx: 0, dy: 0 },
      { element: 'C', dx: 45, dy: 0 },
      { element: 'O', dx: 85, dy: 0 },
      { element: 'R', dx: -40, dy: 25 },
    ],
    bondSpecs: [{ from: 0, to: 1 }, { from: 1, to: 2, order: 2 }, { from: 2, to: 3, order: 2 }, { from: 1, to: 4 }],
  }),
];